CREATE TABLE IF NOT EXISTS `todos` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  is_finished INT(1) DEFAULT 0,
  is_active INT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `tags` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  is_active INT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `todos_tags` (
  todo_id INT UNSIGNED,
  tags_id INT UNSIGNED,
  PRIMARY KEY (todo_id, tags_id),
  FOREIGN KEY (todo_id) REFERENCES todos (id),
  FOREIGN KEY (tags_id) REFERENCES tags (id)
) ENGINE = INNODB;
